language: objective-c
osx_image: xcode8
install:
  - gem install xcpretty
  - rake setup
env:
  - ACTION=test:osx
  - ACTION=test:ios
  - ACTION=test:tvos
  - ACTION=test:watchos
  - ACTION=build:all
script: rake "$ACTION"
